name: terraform-checks

on:
  push:
    branches: [ main ]

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.0
      - run: find . -type f -name "*.tfvars" -delete # remove terraform variable files before linting
      - run: tflint --version
      - run: tflint --init
      - run: tflint --format compact -c $(realpath .tflint.hcl)

